# Generated by Django 5.1 on 2024-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomoe', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
            ],
        ),
    ]
